### PR TITLE
Added How to Edit Single Player progress

### PR DESCRIPTION
**Pull request by KapuDaKoopa**
I like to contribute. lol

# Changes

Change Number | Description
-------------------|-------------
1 | Added How to Edit Single Player progress help file

### CODE REVIEW

**Comment by MCMiners9** [comment]
Thank you! I'll be sure to merge this!

**Comment by MCMiners9** [comment]
Merge successful! Thank you for your contributions to the SplatAIO!

**Comment by MCMiners9** [comment]
Why do you impersonate KapuDaKoopa?

**Comment by KapuDaKoopa** [comment]
im the real kapudakoopa. what are you talking about?

**Comment by KapuDaKoopa** [comment]
im the real kapudakoopa. what are you talking about?

**Pull request merged**
