### PR TITLE
plz accept my pull requests

### PR DESCRIPTION
**Pull request by KapuDaKoopa**
I just want to be able to use splatoon aio. and to contribute to it.

### CODE REVIEW

**Comment by MCMiners9** [comment]
Let's see what you did.

**Comment by MCMiners9** [comment]
Lemme consult Deck of Noobs to see what's up. Even though you are a faker.

**Comment by MCMiners9** [comment]
Denied

**Comment by DeckOfNoobs** [comment]
next time, don't plagerize

**Pull request closed without merging**
